
path: D:\CropFairy\AI\data  # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\train  # val images (relative to 'path')

# Classes
names: ['A7', 'A8', 'B3', 'B6', 'B7', 'B8', 'C7']
nc: 7